Update dependency pytest to v8.3.1 (#117)
This PR contains the following updates:

| Package | Type | Update | Change | Pending |
|---|---|---|---|---|
| [pytest](https://togithub.com/pytest-dev/pytest)
([changelog](https://docs.pytest.org/en/stable/changelog.html)) |
project.optional-dependencies | minor | `==8.2.2` -> `==8.3.1` | `8.3.2`
|

---

### Release Notes

<details>
<summary>pytest-dev/pytest (pytest)</summary>

###
[`v8.3.1`](https://togithub.com/pytest-dev/pytest/releases/tag/8.3.1)

[Compare
Source](https://togithub.com/pytest-dev/pytest/compare/8.3.0...8.3.1)

# pytest 8.3.1 (2024-07-20)

The 8.3.0 release failed to include the change notes and docs for the
release. This patch release remedies this. There are no other changes.

###
[`v8.3.0`](https://togithub.com/pytest-dev/pytest/releases/tag/8.3.0)

[Compare
Source](https://togithub.com/pytest-dev/pytest/compare/8.2.2...8.3.0)

### pytest 8.3.0 (2024-07-20)

#### New features

- [#&#8203;12231](https://togithub.com/pytest-dev/pytest/issues/12231):
Added \[--xfail-tb]{.title-ref} flag, which turns on traceback output
for XFAIL results.

- If the \[--xfail-tb]{.title-ref} flag is not given, tracebacks for
XFAIL results are NOT shown.
- The style of traceback for XFAIL is set with \[--tb]{.title-ref}, and
can be \[auto|long|short|line|native|no]{.title-ref}.
- Note: Even if you have \[--xfail-tb]{.title-ref} set, you won't see
them if \[--tb=no]{.title-ref}.

    Some history:

With pytest 8.0, \[-rx]{.title-ref} or \[-ra]{.title-ref} would not only
turn on summary reports for xfail, but also report the tracebacks for
xfail results. This caused issues with some projects that utilize xfail,
but don't want to see all of the xfail tracebacks.

This change detaches xfail tracebacks from \[-rx]{.title-ref}, and now
we turn on xfail tracebacks with \[--xfail-tb]{.title-ref}. With this,
the default \[-rx]{.title-ref}/ \[-ra]{.title-ref} behavior is identical
to pre-8.0 with respect to xfail tracebacks. While this is a behavior
change, it brings default behavior back to pre-8.0.0 behavior, which
ultimately was considered the better course of action.

- [#&#8203;12281](https://togithub.com/pytest-dev/pytest/issues/12281):
Added support for keyword matching in marker expressions.

    Now tests can be selected by marker keyword arguments.
Supported values are `int`{.interpreted-text role="class"}, (unescaped)
`str`{.interpreted-text role="class"}, `bool`{.interpreted-text
role="class"} & `None`{.interpreted-text role="data"}.

See `marker examples
<marker_keyword_expression_example>`{.interpreted-text role="ref"} for
more information.

    \-- by `lovetheguitar`{.interpreted-text role="user"}

- [#&#8203;12567](https://togithub.com/pytest-dev/pytest/issues/12567):
Added `--no-fold-skipped` command line option.

If this option is set, then skipped tests in short summary are no longer
grouped
by reason but all tests are printed individually with their nodeid in
the same
    way as other statuses.

    \-- by `pbrezina`{.interpreted-text role="user"}

#### Improvements in existing functionality

- [#&#8203;12469](https://togithub.com/pytest-dev/pytest/issues/12469):
The console output now uses the "third-party plugins" terminology,
    replacing the previously established but confusing and outdated
reference to `setuptools <setuptools:index>`{.interpreted-text
role="std:doc"}
    \-- by `webknjaz`{.interpreted-text role="user"}.

- [#&#8203;12544](https://togithub.com/pytest-dev/pytest/issues/12544),
[#&#8203;12545](https://togithub.com/pytest-dev/pytest/issues/12545):
Python virtual environment detection was improved by
checking for a `pyvenv.cfg`{.interpreted-text role="file"} file,
ensuring reliable detection on
various platforms -- by `zachsnickers`{.interpreted-text role="user"}.

- [#&#8203;2871](https://togithub.com/pytest-dev/pytest/issues/2871): Do
not truncate arguments to functions in output when running with
\[-vvv]{.title-ref}.

- [#&#8203;389](https://togithub.com/pytest-dev/pytest/issues/389): The
readability of assertion introspection of bound methods has been
enhanced
\-- by `farbodahm`{.interpreted-text role="user"},
`webknjaz`{.interpreted-text role="user"},
`obestwalter`{.interpreted-text role="user"}, `flub`{.interpreted-text
role="user"}
    and `glyphack`{.interpreted-text role="user"}.

    Earlier, it was like:

    ```console
=================================== FAILURES
===================================
_____________________________________ test
_____________________________________

        def test():
    >       assert Help().fun() == 2
    E       assert 1 == 2
E + where 1 = <bound method Help.fun of <example.Help instance at
0x256a830>>()
E + where <bound method Help.fun of <example.Help instance at
0x256a830>> = <example.Help instance at 0x256a830>.fun
    E        +      where <example.Help instance at 0x256a830> = Help()

    example.py:7: AssertionError
=========================== 1 failed in 0.03 seconds
===========================
    ```

    And now it's like:

    ```console
=================================== FAILURES
===================================
_____________________________________ test
_____________________________________

        def test():
    >       assert Help().fun() == 2
    E       assert 1 == 2
    E        +  where 1 = fun()
E + where fun = <test_local.Help object at 0x1074be230>.fun
E + where <test_local.Help object at 0x1074be230> = Help()

    test_local.py:13: AssertionError
=========================== 1 failed in 0.03 seconds
===========================
    ```

- [#&#8203;7662](https://togithub.com/pytest-dev/pytest/issues/7662):
Added timezone information to the testsuite timestamp in the JUnit XML
report.

#### Bug fixes

- [#&#8203;11706](https://togithub.com/pytest-dev/pytest/issues/11706):
Fixed reporting of teardown errors in higher-scoped fixtures when using
\[--maxfail]{.title-ref} or \[--stepwise]{.title-ref}.

Originally added in pytest 8.0.0, but reverted in 8.0.2 due to a
regression in pytest-xdist.
    This regression was fixed in pytest-xdist 3.6.1.

- [#&#8203;11797](https://togithub.com/pytest-dev/pytest/issues/11797):
`pytest.approx`{.interpreted-text role="func"} now correctly handles
`Sequence <collections.abc.Sequence>`{.interpreted-text
role="class"}-like objects.

- [#&#8203;12204](https://togithub.com/pytest-dev/pytest/issues/12204),
[#&#8203;12264](https://togithub.com/pytest-dev/pytest/issues/12264):
Fixed a regression in pytest 8.0 where tracebacks get longer and longer
when multiple
tests fail due to a shared higher-scope fixture which raised -- by
`bluetech`{.interpreted-text role="user"}.

Also fixed a similar regression in pytest 5.4 for collectors which raise
during setup.

    The fix necessitated internal changes which may affect some plugins:

    -   `FixtureDef.cached_result[2]` is now a tuple `(exc, tb)`
        instead of `exc`.
    -   `SetupState.stack` failures are now a tuple `(exc, tb)`
        instead of `exc`.

- [#&#8203;12275](https://togithub.com/pytest-dev/pytest/issues/12275):
Fixed collection error upon encountering an `abstract
<abc>`{.interpreted-text role="mod"} class, including abstract
\[unittest.TestCase]{.title-ref} subclasses.

- [#&#8203;12328](https://togithub.com/pytest-dev/pytest/issues/12328):
Fixed a regression in pytest 8.0.0 where package-scoped parameterized
items were not correctly reordered to minimize setups/teardowns in some
cases.

- [#&#8203;12424](https://togithub.com/pytest-dev/pytest/issues/12424):
Fixed crash with \[assert testcase is not None]{.title-ref} assertion
failure when re-running unittest tests using plugins like
pytest-rerunfailures. Regressed in 8.2.2.

- [#&#8203;12472](https://togithub.com/pytest-dev/pytest/issues/12472):
Fixed a crash when returning category `"error"` or `"failed"` with a
custom test status from `pytest_report_teststatus`{.interpreted-text
role="hook"} hook -- `pbrezina`{.interpreted-text role="user"}.

- [#&#8203;12505](https://togithub.com/pytest-dev/pytest/issues/12505):
Improved handling of invalid regex patterns in
`pytest.raises(match=r'...') <pytest.raises>`{.interpreted-text
role="func"} by providing a clear error message.

- [#&#8203;12580](https://togithub.com/pytest-dev/pytest/issues/12580):
Fixed a crash when using the cache class on Windows and the cache
directory was created concurrently.

- [#&#8203;6962](https://togithub.com/pytest-dev/pytest/issues/6962):
Parametrization parameters are now compared using \[==]{.title-ref}
instead of \[is]{.title-ref} (\[is]{.title-ref} is still used as a
fallback if the parameter does not support \[==]{.title-ref}).
This fixes use of parameters such as lists, which have a different
\[id]{.title-ref} but compare equal, causing fixtures to be re-computed
instead of being cached.

- [#&#8203;7166](https://togithub.com/pytest-dev/pytest/issues/7166):
Fixed progress percentages (the `[ 87%]` at the edge of the screen)
sometimes not aligning correctly when running with pytest-xdist `-n`.

#### Improved documentation

- [#&#8203;12153](https://togithub.com/pytest-dev/pytest/issues/12153):
Documented using `PYTEST_VERSION`{.interpreted-text role="envvar"} to
detect if code is running from within a pytest run.

- [#&#8203;12469](https://togithub.com/pytest-dev/pytest/issues/12469):
The external plugin mentions in the documentation now avoid mentioning
`setuptools entry-points <setuptools:index>`{.interpreted-text
role="std:doc"} as the concept is
    much more generic nowadays. Instead, the terminology of "external",
    "installed", or "third-party" plugins (or packages) replaces that.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12577](https://togithub.com/pytest-dev/pytest/issues/12577):
\[CI]{.title-ref} and \[BUILD_NUMBER]{.title-ref} environment variables
role is discribed in
the reference doc. They now also appear when doing \[pytest
-h]{.title-ref}
    \-- by `MarcBresson`{.interpreted-text role="user"}.

#### Contributor-facing changes

- [#&#8203;12467](https://togithub.com/pytest-dev/pytest/issues/12467):
Migrated all internal type-annotations to the python3.10+ style by using
the \[annotations]{.title-ref} future import.

    \-- by `RonnyPfannschmidt`{.interpreted-text role="user"}

- [#&#8203;11771](https://togithub.com/pytest-dev/pytest/issues/11771),
[#&#8203;12557](https://togithub.com/pytest-dev/pytest/issues/12557):
The PyPy runtime version has been updated to 3.9 from 3.8 that
introduced
a flaky bug at the garbage collector which was not expected to fix there
    as the 3.8 is EoL.

    \-- by `x612skm`{.interpreted-text role="user"}

- [#&#8203;12493](https://togithub.com/pytest-dev/pytest/issues/12493):
The change log draft preview integration has been refactored to use a
    third party extension `sphinxcontib-towncrier`. The previous in-repo
    script was putting the change log preview file at
`doc/en/_changelog_towncrier_draft.rst`{.interpreted-text role="file"}.
Said file is no longer
    ignored in Git and might show up among untracked files in the
    development environments of the contributors. To address that, the
    contributors can run the following command that will clean it up:

    ```console
    $ git clean -x -i -- doc/en/_changelog_towncrier_draft.rst
    ```

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12498](https://togithub.com/pytest-dev/pytest/issues/12498):
All the undocumented `tox` environments now have descriptions.
    They can be listed in one's development environment by invoking
    `tox -av` in a terminal.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12501](https://togithub.com/pytest-dev/pytest/issues/12501):
The changelog configuration has been updated to introduce more accurate
    audience-tailored categories. Previously, there was a `trivial`
    change log fragment type with an unclear and broad meaning. It was
    removed and we now have `contrib`, `misc` and `packaging` in
    place of it.

    The new change note types target the readers who are downstream
    packagers and project contributors. Additionally, the miscellaneous
section is kept for unspecified updates that do not fit anywhere else.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12502](https://togithub.com/pytest-dev/pytest/issues/12502):
The UX of the GitHub automation making pull requests to update the
plugin list has been updated. Previously, the maintainers had to close
the automatically created pull requests and re-open them to trigger the
CI runs. From now on, they only need to click the \[Ready for
review]{.title-ref}
    button instead.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12522](https://togithub.com/pytest-dev/pytest/issues/12522):
The `:pull:` RST role has been replaced with a shorter
    `:pr:` due to starting to use the implementation from
the third-party `sphinx-issues`{.interpreted-text role="pypi"} Sphinx
extension
    \-- by `webknjaz`{.interpreted-text role="user"}.

- [#&#8203;12531](https://togithub.com/pytest-dev/pytest/issues/12531):
The coverage reporting configuration has been updated to exclude
    pytest's own tests marked as expected to fail from the coverage
    report. This has an effect of reducing the influence of flaky
    tests on the resulting number.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12533](https://togithub.com/pytest-dev/pytest/issues/12533):
The `extlinks` Sphinx extension is no longer enabled. The `:bpo:`
    role it used to declare has been removed with that. BPO itself has
    migrated to GitHub some years ago and it is possible to link the
    respective issues by using their GitHub issue numbers and the
    `:issue:` role that the `sphinx-issues` extension implements.

    \-- by `webknjaz`{.interpreted-text role="user"}

- [#&#8203;12562](https://togithub.com/pytest-dev/pytest/issues/12562):
Possible typos in using the `:user:` RST role is now being linted
through the pre-commit tool integration -- by
`webknjaz`{.interpreted-text role="user"}.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://togithub.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC44LjUiLCJ1cGRhdGVkSW5WZXIiOiIzOC44LjUiLCJ0YXJnZXRCcmFuY2giOiJtYWluIiwibGFiZWxzIjpbXX0=-->

---------

Co-authored-by: Nicolas Drebenstedt <drebenstedtn@rki.de>